name: math-review
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12.4
  - numpy==2.0.0
  - xarray=2024.6.0
  - pandas==2.2.2
  - matplotlib==3.9.1
  - jupyter==1.0.0
  - ipython==5.5.0
  - netcdf4==1.7.1
  - dask==2024.7.0
  - scipy==1.14.0